- name: Delete user password expiration
  hosts: all
  become: yes

  tasks:
  - name: Modify expiration date
    shell: chage -m 0 -M 99999 -I -1 -E -1 {{ item }}
    with_items:
      - naiaragarcia
