- name: Delete admin 
  hosts: all 
  become: yes
  gather_facts: no
  vars_prompt:
    - name: "user"
      prompt: "Which is the username?"

  tasks:
  - name: Remove user
    user:
      name: "{{ user }}"
      state: absent
      remove: yes

  - name: Delete line at /etc/sudoers
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: '^{{ user }} '
      validate: '/usr/sbin/visudo -cf %s'
