---
# tasks file for exportar_logs

- name: Instalar nfs
  yum:
    name: nfs-utils
    state: latest

- name: Arrancar NFS
  service:
    name: nfs
    state: started
    enabled: yes
  
- name: Añadir líneas al fichero /etc/exports
  lineinfile:
    path: /etc/exports
    line: "{{ item.value }} srvcceasfsl01(ro)"
  loop: "{{ query('dict', paths) }}"
  notify: Reinicio nfs
